feature: support subdirectories for debug dumps
matter-labs/era-compiler-llvm-context pull request #24
Opened 2024-04-13 14:11 UTC by sayon

# What ❔

Support creating subfolders in `debug/`.

## Why ❔

Compiler tester overrides IR dumps if they were produced by launching a test repeatedly with different modes.

2024-04-13 15:17 UTC, hedgar2017 requested changes

2024-04-13 15:17 UTC, hedgar2017 commented on src/debug_config/mod.rs
> +    /// Rules to encode a string into a valid filename
A full stop please.

2024-04-13 15:17 UTC, hedgar2017 commented on src/debug_config/mod.rs
> +    fn sanitize(string: &str) -> String {
Add `sanitize_<what>` please.

2024-04-13 15:17 UTC, hedgar2017 commented on src/debug_config/mod.rs
> +        let subdirectory_path = self.output_directory.join(sanitized_name);
Please take a reference here instead.

2024-04-13 15:17 UTC, hedgar2017 commented on src/debug_config/mod.rs
> +        std::fs::create_dir_all(subdirectory_path.clone())?;
This method should be accepting a reference as well.
If it's `PathBuf`, `.as_path()` can be used.

2024-04-14 17:19 UTC, hedgar2017 requested changes

2024-04-14 17:19 UTC, hedgar2017 commented on src/debug_config/mod.rs
> +        let sanitized_name = &Self::sanitize_filename_fragment(directory_name);
This & is redundant then.

2024-04-14 17:36 UTC, hedgar2017 approved these changes

2024-04-14 17:36 UTC, merged

2024-04-16 10:41 UTC, hedgar2017 commented on src/debug_config/mod.rs
> -        let mut full_file_name = contract_path.replace('/', "_").replace(':', ".");
@sayon just noticed the missing `:`.
Can cause issues on Windows.

2024-04-16 10:55 UTC, sayon commented on src/debug_config/mod.rs
> -        let mut full_file_name = contract_path.replace('/', "_").replace(':', ".");
And colon does cause issues on Android (don't ask how I have discovered that :x )