ci: add build and test workflow
matter-labs/era-compiler-llvm-context pull request #44
Opened 2024-09-24 14:15 UTC by antonbaliasnikov

# What ❔

Add `cargo build` and `cargo test` into the workflow.

## Why ❔

To build and test repository with each PR and commit.

## Checklist

- [x] PR title corresponds to the body of PR.
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.

2024-09-24 16:32 UTC, hedgar2017 approved these changes

2024-09-24 16:33 UTC, hedgar2017 requested changes
In the PR I can only see Linux x64 results. Is it OK?

2024-09-24 20:04 UTC, antonbaliasnikov commented
> In the PR I can only see Linux x64 results. Is it OK?

I was wondering if we need other platforms or not. What do you think? I can add others as well, but at the same time didn't want to use lots of runners resources.

2024-09-25 03:53 UTC, hedgar2017 commented
> > In the PR I can only see Linux x64 results. Is it OK?
> 
> 
> 
> I was wondering if we need other platforms or not. What do you think? I can add others as well, but at the same time didn't want to use lots of runners resources.

Yeah, building LLVM on every commit here would be too much.

2024-09-25 03:53 UTC, hedgar2017 approved these changes

2024-09-25 03:53 UTC, merged